# Generated by Django 5.2 on 2025-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for payments', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('AMAZON', 'Amazon Pay'), ('GPAY', 'Google Pay'), ('PAYTM', 'Paytm'), ('UPI', 'UPI Payment'), ('OTHER', 'Other')], default='UPI', max_length=10),
        ),
    ]
